<a href="https://colab.research.google.com/github/Abigail-Ashley-Cayco/58013_Linear_Algebra/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy
A=numpy.array([[4, 7, 8],
               [-9, 0, 0],
               [2, 3, 4]])
print(A)
print(int(numpy.linalg.det(A)))

[[ 4  7  8]
 [-9  0  0]
 [ 2  3  4]]
36


In [7]:
import numpy
A=numpy.array([[2, 3, -5],
               [7, 1, -2],
               [-3, 4, 1]])
print(A)
print(int(numpy.linalg.det(A)))

[[ 2  3 -5]
 [ 7  1 -2]
 [-3  4  1]]
-140


Practice

In [8]:
import numpy
A=numpy.array([[1, 2, -1],
               [4, 6, -2],
               [-1, 3, 3]])
print(A)
print(int(numpy.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6 -2]
 [-1  3  3]]
-13
