<a href="https://colab.research.google.com/github/Abigail-Ashley-Cayco/58013_Linear_Algebra/blob/main/Laboratory_Activity_No_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
A = np.array([1,2,0])
B = np.array([3,1,-2])
C = np.array([0,0,1])
A+B+C
np.add(A,np.add(B,C))
np.sum(B)

2

In [4]:
np.subtract(A,B)
A-B

array([-2,  1,  2])

In [5]:
np.multiply(A,B)

A*B

array([3, 2, 0])

In [7]:
np.divide(A,B)

print(A/B)

C = np.array([3.9,1.8,7.7])
D = np.array([1,1,1])
print(C//D)

np.array(A/B,dtype=int)

[ 0.33333333  2.         -0.        ]
[3. 1. 7.]


array([0, 2, 0])