<a href="https://colab.research.google.com/github/Abigail-Ashley-Cayco/58013_Linear_Algebra/blob/main/Lec_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
x = np.array(-0.5)
x

array(-0.5)

Vectors

In [4]:
A = np.array([4,3])
B = np.array([2, -5])
print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


Describing Vectors in NumPy

In [7]:
### Checking shapes
### Shapes tells us how many rows and columns are there
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
pool = np.array([ball1,ball2]) ## Matrix
pool.shape

U = np.array([
    [1,2],
    [2,3]
])
U.shape

## Checking size
## Array/Vector sizes tells us many total number of elements are there in the vector

U.size

## Checking dimensions
### The dimension or rank of a vector tells us how many dimension are there for the vectors.
A.ndim
pool.ndim

2

In [ ]:
#Size Dimension, Size
import numpy as np
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])
print(ball1)
print(ball2)
#ball = np.shape([[ball1]],[ball2]])
ball=np.shape(ball1)
balls=np.shape(ball2)
z= ball+balls
print(z)

[1 2 3]
[ 0  1 -1]
(3,)


Addition

In [ ]:
#addition
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])
R = np.add(A,B)
print(R)

[ 6 -2]


In [ ]:
#Subraction
import numpy as np
R1 = np.subtract(A,B)
print(R1)
R2 = np.subtract(B,A)
print(R2)

[2 8]
[-2 -8]


In [ ]:
#Scalar Product
import numpy as np
S = np.array([2])
V = S*A
print(V)

[8 6]


In [ ]:
#Multiplication
import numpy as np
A = np.array([4,3])
B = np.array(([2],[-5]))
print(B*A)

[[  8   6]
 [-20 -15]]


In [ ]:
#Dot Product
A = np.array([4,3])
B = np.array(([2],[-5]))
print(np.dot(A,B))

[-7]


In [ ]:
#Property Matrix
#Identity Matrix
c = np.eye(3,3)
print(c)

#zero matrix
d = np.zeros([5,5])
print("\n", d)
#Full matrix
e = np.full((3,3),7)
print("\n", e)
#Transpose Matrix
f = np.transpose(A)
print("\n",f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 [4 3]


In [ ]:
#Transpose of Matrix
import numpy as np
A = np.array([4,3])
B = np.array(([2],[-5]))
print(B*A)
f = np.transpose(A)
print("\n",f)

[[  8   6]
 [-20 -15]]

 [4 3]
