<a href="https://colab.research.google.com/github/Abigail-Ashley-Cayco/58013_Linear_Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem # 1

In [9]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[1, 2],
              [3, 4],
              [5, 6]])
C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
D = np.array([[1, 2],
              [3, 4]])
# a.) AB
print("a.) AB\n", np.dot(A, B))

# b.) D + D
print("\n b.) D + D\n", np.add(D,D))

# c.) 2C
print("\n c.) 2C \n", np.multiply(2, C))

a.) AB
 [[22 28]
 [49 64]]

 b.) D + D
 [[2 4]
 [6 8]]

 c.) 2C 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem #2. Find the cross-product of matrices, A = [2,7,4] and
B = [3,9,8]. Show your solutions using Python program .

In [2]:
import numpy as np
A = np.array([2,7,4])
B = np.array([3,9,8])
print(np.cross(A,B))

[20 -4 -3]
