<a href="https://colab.research.google.com/github/Abigail-Ashley-Cayco/58013_Linear_Algebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than (3,3). In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)

-235.0000000000002

Associative:

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
C = np.array([[2, 3, 4],
              [5, 6, 7],
              [8, 9, 10]])
Associative1 = np.dot(np.dot(A, B), C)
Associative2 = np.dot(A, np.dot(B, C))
print("Associative 1:")
print(Associative1)
print("Associative 2:")
print(Associative2)
print("This proves that (A*B)*C is equal to A*(B*C)")

Associative 1:
[[ 324  396  468]
 [ 945 1152 1359]
 [1566 1908 2250]]
Associative 2:
[[ 324  396  468]
 [ 945 1152 1359]
 [1566 1908 2250]]
This proves that (A*B)*C is equal to A*(B*C)


Distributive

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
C = np.array([[2, 3, 4],
              [5, 6, 7],
              [8, 9, 10]])
Distributive1 = np.dot(A, B + C)
Distributive2 = np.dot(A, B) + np.dot(A, C)

print("Distributive 1:")
print(Distributive1)
print("Distributive 2:")
print(Distributive2)
print("This proves that A*(B+C) is equal to A*B+A*C")

Distributive 1:
[[ 66  66  66]
 [165 165 165]
 [264 264 264]]
Distributive 2:
[[ 66  66  66]
 [165 165 165]
 [264 264 264]]
This proves that A*(B+C) is equal to A*B+A*C


Scalar

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
C = 2
Scalar1 = C * np.dot(A, B)
Scalar2 = np.dot(C * A, B)

print("Scalar 1:")
print(Scalar1)
print("Scalar 2:")
print(Scalar2)
print("This proves that C*(A*B) is equal to (C*A)*B")

Scalar 1:
[[ 60  48  36]
 [168 138 108]
 [276 228 180]]
Scalar 2:
[[ 60  48  36]
 [168 138 108]
 [276 228 180]]
This proves that C*(A*B) is equal to (C*A)*B


Commutative

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
Commutative1 = np.dot(A, B)
Commutative2 = np.dot(B, A)

print("Commutative 1:")
print(Commutative1)
print("Commutative 2:")
print(Commutative2)
print("This proves that A*B is not necessarily equal to B*A")

Commutative 1:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Commutative 2:
[[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]]
This proves that A*B is not necessarily equal to B*A


 Identity Matrix

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
I = np.identity(3)
IdentityMatrix = np.dot(I, A)

print("Identity Matrix:")
print(IdentityMatrix)
print("This states that I*A is equal to A where I is the Identity Matrix")

Identity Matrix:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
This states that I*A is equal to A where I is the Identity Matrix


Zero Matrix

In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
ZeroMatrix = np.zeros((3, 3))
ZeroMatrix1 = np.dot(zero_matrix, A)

print("ZeroMatrix1:")
print(ZeroMatrix1)
print("This states that 0*A is equal to the zero matrix, where 0 is a matrix of all zeros")

ZeroMatrix1:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
This states that 0*A is equal to the zero matrix, where 0 is a matrix of all zeros
